name: Environment Deployment

on:
  push:
    branches:
      - patch-1
  workflow_dispatch:
    inputs:
      ref:
        type: choice
        description: 'Select a reference'
        required: true
        options:
          - 'patch-1'
          - 'main'
      environment:
        type: choice
        description: Choose an environment
        options:
          - "QA-Internal"
          - "DEV"
          

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to selected environment
        run: |
          environment="${{ github.event.inputs.environment }}"
          echo "Deploying to $environment environment..."
          
