name: Environment Deployment

on:
  push:
    branches:
      - patch
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an environment
        options:
          - "QA-Internal"
          - "DEV"   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to selected environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/patch-1" ]; then
            environment="QA-Internal"
            echo "Deploying to $environment environment..."
          fi
          
